// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "reduce_2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic reduce_2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic reduce_2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> reduce_2::ap_ST_fsm_state1 = "1";
const sc_lv<6> reduce_2::ap_ST_fsm_state2 = "10";
const sc_lv<6> reduce_2::ap_ST_fsm_state3 = "100";
const sc_lv<6> reduce_2::ap_ST_fsm_state4 = "1000";
const sc_lv<6> reduce_2::ap_ST_fsm_state5 = "10000";
const sc_lv<6> reduce_2::ap_ST_fsm_state6 = "100000";
const sc_lv<32> reduce_2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> reduce_2::ap_const_lv32_1 = "1";
const sc_lv<32> reduce_2::ap_const_lv32_4 = "100";
const sc_lv<1> reduce_2::ap_const_lv1_0 = "0";
const sc_lv<1> reduce_2::ap_const_lv1_1 = "1";
const sc_lv<4> reduce_2::ap_const_lv4_0 = "0000";
const sc_lv<32> reduce_2::ap_const_lv32_3 = "11";
const sc_lv<4> reduce_2::ap_const_lv4_1 = "1";
const sc_lv<4> reduce_2::ap_const_lv4_2 = "10";
const sc_lv<4> reduce_2::ap_const_lv4_3 = "11";
const sc_lv<4> reduce_2::ap_const_lv4_4 = "100";
const sc_lv<4> reduce_2::ap_const_lv4_5 = "101";
const sc_lv<4> reduce_2::ap_const_lv4_6 = "110";
const sc_lv<2> reduce_2::ap_const_lv2_0 = "00";
const sc_lv<32> reduce_2::ap_const_lv32_5 = "101";
const sc_lv<32> reduce_2::ap_const_lv32_2 = "10";
const sc_lv<3> reduce_2::ap_const_lv3_0 = "000";
const sc_lv<3> reduce_2::ap_const_lv3_1 = "1";
const sc_lv<3> reduce_2::ap_const_lv3_2 = "10";
const sc_lv<3> reduce_2::ap_const_lv3_3 = "11";
const sc_lv<3> reduce_2::ap_const_lv3_4 = "100";
const sc_lv<3> reduce_2::ap_const_lv3_5 = "101";
const sc_lv<3> reduce_2::ap_const_lv3_6 = "110";
const sc_lv<3> reduce_2::ap_const_lv3_7 = "111";
const sc_lv<4> reduce_2::ap_const_lv4_8 = "1000";
const sc_lv<2> reduce_2::ap_const_lv2_2 = "10";
const sc_lv<2> reduce_2::ap_const_lv2_1 = "1";
const sc_lv<12> reduce_2::ap_const_lv12_0 = "000000000000";
const bool reduce_2::ap_const_boolean_1 = true;

reduce_2::reduce_2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_reduce_fu_230 = new reduce("grp_reduce_fu_230");
    grp_reduce_fu_230->ap_clk(ap_clk);
    grp_reduce_fu_230->ap_rst(ap_rst);
    grp_reduce_fu_230->ap_start(grp_reduce_fu_230_ap_start);
    grp_reduce_fu_230->ap_done(grp_reduce_fu_230_ap_done);
    grp_reduce_fu_230->ap_idle(grp_reduce_fu_230_ap_idle);
    grp_reduce_fu_230->ap_ready(grp_reduce_fu_230_ap_ready);
    grp_reduce_fu_230->x_0_V_read(left_7_V_fu_70);
    grp_reduce_fu_230->x_1_V_read(left_7_V_1_fu_74);
    grp_reduce_fu_230->x_2_V_read(left_7_V_2_fu_78);
    grp_reduce_fu_230->x_3_V_read(left_7_V_3_fu_82);
    grp_reduce_fu_230->x_4_V_read(left_7_V_4_fu_86);
    grp_reduce_fu_230->x_5_V_read(left_7_V_5_fu_90);
    grp_reduce_fu_230->x_6_V_read(left_7_V_6_fu_94);
    grp_reduce_fu_230->x_7_V_read(left_7_V_7_fu_98);
    grp_reduce_fu_230->ap_return(grp_reduce_fu_230_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_1_fu_360_p2);
    sensitive << ( grp_reduce_fu_230_ap_return );
    sensitive << ( p_Val2_s_reg_207 );

    SC_METHOD(thread_add_ln703_fu_366_p2);
    sensitive << ( p_Val2_2_reg_195 );
    sensitive << ( add_ln703_1_fu_360_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_299);
    sensitive << ( ap_phi_mux_i_0_phi_fu_166_p4 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_reduce_fu_230_ap_done );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_166_p4);
    sensitive << ( i_0_reg_162 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_reduce_fu_230_ap_done );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_reduce_fu_230_ap_done );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( add_ln703_fu_366_p2 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_grp_reduce_fu_230_ap_start);
    sensitive << ( grp_reduce_fu_230_ap_start_reg );

    SC_METHOD(thread_i_1_fu_304_p2);
    sensitive << ( i2_0_reg_219 );

    SC_METHOD(thread_i_fu_248_p2);
    sensitive << ( i_0_reg_162 );

    SC_METHOD(thread_icmp_ln74_fu_242_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_162 );

    SC_METHOD(thread_icmp_ln77_fu_298_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i2_0_reg_219 );

    SC_METHOD(thread_right_0_V_1_fu_321_p3);
    sensitive << ( x_8_V_read );
    sensitive << ( p_Val2_s_reg_207 );
    sensitive << ( trunc_ln203_fu_310_p1 );

    SC_METHOD(thread_right_0_V_fu_314_p3);
    sensitive << ( x_9_V_read );
    sensitive << ( p_Val2_2_reg_195 );
    sensitive << ( trunc_ln203_fu_310_p1 );

    SC_METHOD(thread_trunc_ln203_1_fu_254_p1);
    sensitive << ( i_0_reg_162 );

    SC_METHOD(thread_trunc_ln203_fu_310_p1);
    sensitive << ( i2_0_reg_219 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln77_fu_298_p2 );
    sensitive << ( grp_reduce_fu_230_ap_done );
    sensitive << ( icmp_ln74_fu_242_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    ap_CS_fsm = "000001";
    grp_reduce_fu_230_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "reduce_2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x_0_V_read, "(port)x_0_V_read");
    sc_trace(mVcdFile, x_1_V_read, "(port)x_1_V_read");
    sc_trace(mVcdFile, x_2_V_read, "(port)x_2_V_read");
    sc_trace(mVcdFile, x_3_V_read, "(port)x_3_V_read");
    sc_trace(mVcdFile, x_4_V_read, "(port)x_4_V_read");
    sc_trace(mVcdFile, x_5_V_read, "(port)x_5_V_read");
    sc_trace(mVcdFile, x_6_V_read, "(port)x_6_V_read");
    sc_trace(mVcdFile, x_7_V_read, "(port)x_7_V_read");
    sc_trace(mVcdFile, x_8_V_read, "(port)x_8_V_read");
    sc_trace(mVcdFile, x_9_V_read, "(port)x_9_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_248_p2, "i_fu_248_p2");
    sc_trace(mVcdFile, i_reg_473, "i_reg_473");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_304_p2, "i_1_fu_304_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, right_0_V_fu_314_p3, "right_0_V_fu_314_p3");
    sc_trace(mVcdFile, icmp_ln77_fu_298_p2, "icmp_ln77_fu_298_p2");
    sc_trace(mVcdFile, right_0_V_1_fu_321_p3, "right_0_V_1_fu_321_p3");
    sc_trace(mVcdFile, grp_reduce_fu_230_ap_start, "grp_reduce_fu_230_ap_start");
    sc_trace(mVcdFile, grp_reduce_fu_230_ap_done, "grp_reduce_fu_230_ap_done");
    sc_trace(mVcdFile, grp_reduce_fu_230_ap_idle, "grp_reduce_fu_230_ap_idle");
    sc_trace(mVcdFile, grp_reduce_fu_230_ap_ready, "grp_reduce_fu_230_ap_ready");
    sc_trace(mVcdFile, grp_reduce_fu_230_ap_return, "grp_reduce_fu_230_ap_return");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_166_p4, "ap_phi_mux_i_0_phi_fu_166_p4");
    sc_trace(mVcdFile, i_0_reg_162, "i_0_reg_162");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, left_0_V_reg_174, "left_0_V_reg_174");
    sc_trace(mVcdFile, icmp_ln74_fu_242_p2, "icmp_ln74_fu_242_p2");
    sc_trace(mVcdFile, p_Val2_2_reg_195, "p_Val2_2_reg_195");
    sc_trace(mVcdFile, p_Val2_s_reg_207, "p_Val2_s_reg_207");
    sc_trace(mVcdFile, i2_0_reg_219, "i2_0_reg_219");
    sc_trace(mVcdFile, grp_reduce_fu_230_ap_start_reg, "grp_reduce_fu_230_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, left_7_V_fu_70, "left_7_V_fu_70");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, trunc_ln203_1_fu_254_p1, "trunc_ln203_1_fu_254_p1");
    sc_trace(mVcdFile, left_7_V_1_fu_74, "left_7_V_1_fu_74");
    sc_trace(mVcdFile, left_7_V_2_fu_78, "left_7_V_2_fu_78");
    sc_trace(mVcdFile, left_7_V_3_fu_82, "left_7_V_3_fu_82");
    sc_trace(mVcdFile, left_7_V_4_fu_86, "left_7_V_4_fu_86");
    sc_trace(mVcdFile, left_7_V_5_fu_90, "left_7_V_5_fu_90");
    sc_trace(mVcdFile, left_7_V_6_fu_94, "left_7_V_6_fu_94");
    sc_trace(mVcdFile, left_7_V_7_fu_98, "left_7_V_7_fu_98");
    sc_trace(mVcdFile, trunc_ln203_fu_310_p1, "trunc_ln203_fu_310_p1");
    sc_trace(mVcdFile, add_ln703_1_fu_360_p2, "add_ln703_1_fu_360_p2");
    sc_trace(mVcdFile, add_ln703_fu_366_p2, "add_ln703_fu_366_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_299, "ap_condition_299");
#endif

    }
}

reduce_2::~reduce_2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_reduce_fu_230;
}

void reduce_2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv12_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
             esl_seteq<1,1,1>(grp_reduce_fu_230_ap_done.read(), ap_const_logic_1))) {
            ap_return_preg = add_ln703_fu_366_p2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_reduce_fu_230_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             esl_seteq<1,1,1>(icmp_ln77_fu_298_p2.read(), ap_const_lv1_1))) {
            grp_reduce_fu_230_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_reduce_fu_230_ap_ready.read())) {
            grp_reduce_fu_230_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln74_fu_242_p2.read()))) {
        i2_0_reg_219 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln77_fu_298_p2.read(), ap_const_lv1_0))) {
        i2_0_reg_219 = i_1_fu_304_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_0_reg_162 = i_reg_473.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_162 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln74_fu_242_p2.read()))) {
        if (esl_seteq<1,4,4>(ap_const_lv4_0, ap_phi_mux_i_0_phi_fu_166_p4.read())) {
            left_0_V_reg_174 = x_0_V_read.read();
        } else if (esl_seteq<1,1,1>(ap_condition_299.read(), ap_const_boolean_1)) {
            left_0_V_reg_174 = x_7_V_read.read();
        } else if (esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_6)) {
            left_0_V_reg_174 = x_6_V_read.read();
        } else if (esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_5)) {
            left_0_V_reg_174 = x_5_V_read.read();
        } else if (esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_4)) {
            left_0_V_reg_174 = x_4_V_read.read();
        } else if (esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_3)) {
            left_0_V_reg_174 = x_3_V_read.read();
        } else if (esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_2)) {
            left_0_V_reg_174 = x_2_V_read.read();
        } else if (esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_1)) {
            left_0_V_reg_174 = x_1_V_read.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_473 = i_fu_248_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_1))) {
        left_7_V_1_fu_74 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_2))) {
        left_7_V_2_fu_78 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_3))) {
        left_7_V_3_fu_82 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_4))) {
        left_7_V_4_fu_86 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_5))) {
        left_7_V_5_fu_90 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_6))) {
        left_7_V_6_fu_94 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_7))) {
        left_7_V_7_fu_98 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,3,3>(trunc_ln203_1_fu_254_p1.read(), ap_const_lv3_0))) {
        left_7_V_fu_70 = left_0_V_reg_174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln77_fu_298_p2.read(), ap_const_lv1_0))) {
        p_Val2_2_reg_195 = right_0_V_fu_314_p3.read();
        p_Val2_s_reg_207 = right_0_V_1_fu_321_p3.read();
    }
}

void reduce_2::thread_add_ln703_1_fu_360_p2() {
    add_ln703_1_fu_360_p2 = (!p_Val2_s_reg_207.read().is_01() || !grp_reduce_fu_230_ap_return.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_s_reg_207.read()) + sc_biguint<12>(grp_reduce_fu_230_ap_return.read()));
}

void reduce_2::thread_add_ln703_fu_366_p2() {
    add_ln703_fu_366_p2 = (!add_ln703_1_fu_360_p2.read().is_01() || !p_Val2_2_reg_195.read().is_01())? sc_lv<12>(): (sc_biguint<12>(add_ln703_1_fu_360_p2.read()) + sc_biguint<12>(p_Val2_2_reg_195.read()));
}

void reduce_2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void reduce_2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void reduce_2::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void reduce_2::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void reduce_2::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void reduce_2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void reduce_2::thread_ap_condition_299() {
    ap_condition_299 = (!esl_seteq<1,4,4>(ap_const_lv4_0, ap_phi_mux_i_0_phi_fu_166_p4.read()) && !esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_1) && !esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_2) && !esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_3) && !esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_4) && !esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_5) && !esl_seteq<1,4,4>(ap_phi_mux_i_0_phi_fu_166_p4.read(), ap_const_lv4_6));
}

void reduce_2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(grp_reduce_fu_230_ap_done.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void reduce_2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void reduce_2::thread_ap_phi_mux_i_0_phi_fu_166_p4() {
    ap_phi_mux_i_0_phi_fu_166_p4 = i_0_reg_162.read();
}

void reduce_2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(grp_reduce_fu_230_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void reduce_2::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(grp_reduce_fu_230_ap_done.read(), ap_const_logic_1))) {
        ap_return = add_ln703_fu_366_p2.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void reduce_2::thread_grp_reduce_fu_230_ap_start() {
    grp_reduce_fu_230_ap_start = grp_reduce_fu_230_ap_start_reg.read();
}

void reduce_2::thread_i_1_fu_304_p2() {
    i_1_fu_304_p2 = (!i2_0_reg_219.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i2_0_reg_219.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void reduce_2::thread_i_fu_248_p2() {
    i_fu_248_p2 = (!i_0_reg_162.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_162.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void reduce_2::thread_icmp_ln74_fu_242_p2() {
    icmp_ln74_fu_242_p2 = (!i_0_reg_162.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_162.read() == ap_const_lv4_8);
}

void reduce_2::thread_icmp_ln77_fu_298_p2() {
    icmp_ln77_fu_298_p2 = (!i2_0_reg_219.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_219.read() == ap_const_lv2_2);
}

void reduce_2::thread_right_0_V_1_fu_321_p3() {
    right_0_V_1_fu_321_p3 = (!trunc_ln203_fu_310_p1.read()[0].is_01())? sc_lv<12>(): ((trunc_ln203_fu_310_p1.read()[0].to_bool())? p_Val2_s_reg_207.read(): x_8_V_read.read());
}

void reduce_2::thread_right_0_V_fu_314_p3() {
    right_0_V_fu_314_p3 = (!trunc_ln203_fu_310_p1.read()[0].is_01())? sc_lv<12>(): ((trunc_ln203_fu_310_p1.read()[0].to_bool())? x_9_V_read.read(): p_Val2_2_reg_195.read());
}

void reduce_2::thread_trunc_ln203_1_fu_254_p1() {
    trunc_ln203_1_fu_254_p1 = i_0_reg_162.read().range(3-1, 0);
}

void reduce_2::thread_trunc_ln203_fu_310_p1() {
    trunc_ln203_fu_310_p1 = i2_0_reg_219.read().range(1-1, 0);
}

void reduce_2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln74_fu_242_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln77_fu_298_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_reduce_fu_230_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

