// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _softmax_HH_
#define _softmax_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "reduce_2.h"
#include "myproject_mul_mulhbi.h"
#include "softmax_exp_table1.h"
#include "softmax_invert_tag8j.h"

namespace ap_rtl {

struct softmax : public sc_module {
    // Port declarations 37
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > data_0_V_read;
    sc_in< sc_lv<12> > data_1_V_read;
    sc_in< sc_lv<12> > data_2_V_read;
    sc_in< sc_lv<12> > data_3_V_read;
    sc_in< sc_lv<12> > data_4_V_read;
    sc_in< sc_lv<12> > data_5_V_read;
    sc_in< sc_lv<12> > data_6_V_read;
    sc_in< sc_lv<12> > data_7_V_read;
    sc_in< sc_lv<12> > data_8_V_read;
    sc_in< sc_lv<12> > data_9_V_read;
    sc_out< sc_lv<12> > res_0_V;
    sc_out< sc_logic > res_0_V_ap_vld;
    sc_out< sc_lv<12> > res_1_V;
    sc_out< sc_logic > res_1_V_ap_vld;
    sc_out< sc_lv<12> > res_2_V;
    sc_out< sc_logic > res_2_V_ap_vld;
    sc_out< sc_lv<12> > res_3_V;
    sc_out< sc_logic > res_3_V_ap_vld;
    sc_out< sc_lv<12> > res_4_V;
    sc_out< sc_logic > res_4_V_ap_vld;
    sc_out< sc_lv<12> > res_5_V;
    sc_out< sc_logic > res_5_V_ap_vld;
    sc_out< sc_lv<12> > res_6_V;
    sc_out< sc_logic > res_6_V_ap_vld;
    sc_out< sc_lv<12> > res_7_V;
    sc_out< sc_logic > res_7_V_ap_vld;
    sc_out< sc_lv<12> > res_8_V;
    sc_out< sc_logic > res_8_V_ap_vld;
    sc_out< sc_lv<12> > res_9_V;
    sc_out< sc_logic > res_9_V_ap_vld;


    // Module declarations
    softmax(sc_module_name name);
    SC_HAS_PROCESS(softmax);

    ~softmax();

    sc_trace_file* mVcdFile;

    softmax_exp_table1* exp_table1_U;
    softmax_invert_tag8j* invert_table2_U;
    reduce_2* grp_reduce_2_fu_328;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U256;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U257;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U258;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U259;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U260;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U261;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U262;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U263;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U264;
    myproject_mul_mulhbi<1,1,12,8,16>* myproject_mul_mulhbi_U265;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<6> > exp_table1_address0;
    sc_signal< sc_logic > exp_table1_ce0;
    sc_signal< sc_lv<12> > exp_table1_q0;
    sc_signal< sc_lv<6> > exp_table1_address1;
    sc_signal< sc_logic > exp_table1_ce1;
    sc_signal< sc_lv<12> > exp_table1_q1;
    sc_signal< sc_lv<6> > exp_table1_address2;
    sc_signal< sc_logic > exp_table1_ce2;
    sc_signal< sc_lv<12> > exp_table1_q2;
    sc_signal< sc_lv<6> > exp_table1_address3;
    sc_signal< sc_logic > exp_table1_ce3;
    sc_signal< sc_lv<12> > exp_table1_q3;
    sc_signal< sc_lv<6> > exp_table1_address4;
    sc_signal< sc_logic > exp_table1_ce4;
    sc_signal< sc_lv<12> > exp_table1_q4;
    sc_signal< sc_lv<6> > exp_table1_address5;
    sc_signal< sc_logic > exp_table1_ce5;
    sc_signal< sc_lv<12> > exp_table1_q5;
    sc_signal< sc_lv<6> > exp_table1_address6;
    sc_signal< sc_logic > exp_table1_ce6;
    sc_signal< sc_lv<12> > exp_table1_q6;
    sc_signal< sc_lv<6> > exp_table1_address7;
    sc_signal< sc_logic > exp_table1_ce7;
    sc_signal< sc_lv<12> > exp_table1_q7;
    sc_signal< sc_lv<6> > exp_table1_address8;
    sc_signal< sc_logic > exp_table1_ce8;
    sc_signal< sc_lv<12> > exp_table1_q8;
    sc_signal< sc_lv<6> > exp_table1_address9;
    sc_signal< sc_logic > exp_table1_ce9;
    sc_signal< sc_lv<12> > exp_table1_q9;
    sc_signal< sc_lv<6> > invert_table2_address0;
    sc_signal< sc_logic > invert_table2_ce0;
    sc_signal< sc_lv<8> > invert_table2_q0;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<12> > exp_res_0_V_reg_771;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<12> > exp_res_1_V_reg_777;
    sc_signal< sc_lv<12> > exp_res_2_V_reg_783;
    sc_signal< sc_lv<12> > exp_res_3_V_reg_789;
    sc_signal< sc_lv<12> > exp_res_4_V_reg_795;
    sc_signal< sc_lv<12> > exp_res_5_V_reg_801;
    sc_signal< sc_lv<12> > exp_res_6_V_reg_807;
    sc_signal< sc_lv<12> > exp_res_7_V_reg_813;
    sc_signal< sc_lv<12> > exp_res_8_V_reg_819;
    sc_signal< sc_lv<12> > exp_res_9_V_reg_825;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_reduce_2_fu_328_ap_ready;
    sc_signal< sc_logic > grp_reduce_2_fu_328_ap_done;
    sc_signal< sc_logic > grp_reduce_2_fu_328_ap_start;
    sc_signal< sc_logic > grp_reduce_2_fu_328_ap_idle;
    sc_signal< sc_lv<12> > grp_reduce_2_fu_328_ap_return;
    sc_signal< sc_logic > grp_reduce_2_fu_328_ap_start_reg;
    sc_signal< sc_lv<64> > zext_ln250_fu_362_p1;
    sc_signal< sc_lv<64> > zext_ln250_1_fu_377_p1;
    sc_signal< sc_lv<64> > zext_ln250_2_fu_392_p1;
    sc_signal< sc_lv<64> > zext_ln250_3_fu_407_p1;
    sc_signal< sc_lv<64> > zext_ln250_4_fu_422_p1;
    sc_signal< sc_lv<64> > zext_ln250_5_fu_437_p1;
    sc_signal< sc_lv<64> > zext_ln250_6_fu_452_p1;
    sc_signal< sc_lv<64> > zext_ln250_7_fu_467_p1;
    sc_signal< sc_lv<64> > zext_ln250_8_fu_482_p1;
    sc_signal< sc_lv<64> > zext_ln250_9_fu_497_p1;
    sc_signal< sc_lv<64> > zext_ln258_fu_512_p1;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<6> > y_V_fu_352_p4;
    sc_signal< sc_lv<6> > y_V_1_fu_367_p4;
    sc_signal< sc_lv<6> > y_V_2_fu_382_p4;
    sc_signal< sc_lv<6> > y_V_3_fu_397_p4;
    sc_signal< sc_lv<6> > y_V_4_fu_412_p4;
    sc_signal< sc_lv<6> > y_V_5_fu_427_p4;
    sc_signal< sc_lv<6> > y_V_6_fu_442_p4;
    sc_signal< sc_lv<6> > y_V_7_fu_457_p4;
    sc_signal< sc_lv<6> > y_V_8_fu_472_p4;
    sc_signal< sc_lv<6> > y_V_9_fu_487_p4;
    sc_signal< sc_lv<6> > y_V_10_fu_502_p4;
    sc_signal< sc_lv<16> > mul_ln1118_fu_651_p2;
    sc_signal< sc_lv<16> > mul_ln1118_1_fu_658_p2;
    sc_signal< sc_lv<16> > mul_ln1118_2_fu_665_p2;
    sc_signal< sc_lv<16> > mul_ln1118_3_fu_672_p2;
    sc_signal< sc_lv<16> > mul_ln1118_4_fu_679_p2;
    sc_signal< sc_lv<16> > mul_ln1118_5_fu_686_p2;
    sc_signal< sc_lv<16> > mul_ln1118_6_fu_693_p2;
    sc_signal< sc_lv<16> > mul_ln1118_7_fu_700_p2;
    sc_signal< sc_lv<16> > mul_ln1118_8_fu_707_p2;
    sc_signal< sc_lv<16> > mul_ln1118_9_fu_714_p2;
    sc_signal< sc_lv<8> > mul_ln1118_fu_651_p1;
    sc_signal< sc_lv<16> > sext_ln1116_fu_517_p1;
    sc_signal< sc_lv<8> > mul_ln1118_1_fu_658_p1;
    sc_signal< sc_lv<8> > mul_ln1118_2_fu_665_p1;
    sc_signal< sc_lv<8> > mul_ln1118_3_fu_672_p1;
    sc_signal< sc_lv<8> > mul_ln1118_4_fu_679_p1;
    sc_signal< sc_lv<8> > mul_ln1118_5_fu_686_p1;
    sc_signal< sc_lv<8> > mul_ln1118_6_fu_693_p1;
    sc_signal< sc_lv<8> > mul_ln1118_7_fu_700_p1;
    sc_signal< sc_lv<8> > mul_ln1118_8_fu_707_p1;
    sc_signal< sc_lv<8> > mul_ln1118_9_fu_714_p1;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_F;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exp_table1_address0();
    void thread_exp_table1_address1();
    void thread_exp_table1_address2();
    void thread_exp_table1_address3();
    void thread_exp_table1_address4();
    void thread_exp_table1_address5();
    void thread_exp_table1_address6();
    void thread_exp_table1_address7();
    void thread_exp_table1_address8();
    void thread_exp_table1_address9();
    void thread_exp_table1_ce0();
    void thread_exp_table1_ce1();
    void thread_exp_table1_ce2();
    void thread_exp_table1_ce3();
    void thread_exp_table1_ce4();
    void thread_exp_table1_ce5();
    void thread_exp_table1_ce6();
    void thread_exp_table1_ce7();
    void thread_exp_table1_ce8();
    void thread_exp_table1_ce9();
    void thread_grp_reduce_2_fu_328_ap_start();
    void thread_invert_table2_address0();
    void thread_invert_table2_ce0();
    void thread_mul_ln1118_1_fu_658_p1();
    void thread_mul_ln1118_2_fu_665_p1();
    void thread_mul_ln1118_3_fu_672_p1();
    void thread_mul_ln1118_4_fu_679_p1();
    void thread_mul_ln1118_5_fu_686_p1();
    void thread_mul_ln1118_6_fu_693_p1();
    void thread_mul_ln1118_7_fu_700_p1();
    void thread_mul_ln1118_8_fu_707_p1();
    void thread_mul_ln1118_9_fu_714_p1();
    void thread_mul_ln1118_fu_651_p1();
    void thread_res_0_V();
    void thread_res_0_V_ap_vld();
    void thread_res_1_V();
    void thread_res_1_V_ap_vld();
    void thread_res_2_V();
    void thread_res_2_V_ap_vld();
    void thread_res_3_V();
    void thread_res_3_V_ap_vld();
    void thread_res_4_V();
    void thread_res_4_V_ap_vld();
    void thread_res_5_V();
    void thread_res_5_V_ap_vld();
    void thread_res_6_V();
    void thread_res_6_V_ap_vld();
    void thread_res_7_V();
    void thread_res_7_V_ap_vld();
    void thread_res_8_V();
    void thread_res_8_V_ap_vld();
    void thread_res_9_V();
    void thread_res_9_V_ap_vld();
    void thread_sext_ln1116_fu_517_p1();
    void thread_y_V_10_fu_502_p4();
    void thread_y_V_1_fu_367_p4();
    void thread_y_V_2_fu_382_p4();
    void thread_y_V_3_fu_397_p4();
    void thread_y_V_4_fu_412_p4();
    void thread_y_V_5_fu_427_p4();
    void thread_y_V_6_fu_442_p4();
    void thread_y_V_7_fu_457_p4();
    void thread_y_V_8_fu_472_p4();
    void thread_y_V_9_fu_487_p4();
    void thread_y_V_fu_352_p4();
    void thread_zext_ln250_1_fu_377_p1();
    void thread_zext_ln250_2_fu_392_p1();
    void thread_zext_ln250_3_fu_407_p1();
    void thread_zext_ln250_4_fu_422_p1();
    void thread_zext_ln250_5_fu_437_p1();
    void thread_zext_ln250_6_fu_452_p1();
    void thread_zext_ln250_7_fu_467_p1();
    void thread_zext_ln250_8_fu_482_p1();
    void thread_zext_ln250_9_fu_497_p1();
    void thread_zext_ln250_fu_362_p1();
    void thread_zext_ln258_fu_512_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
